services:
  backend:
    build:
      context: './backend'
      target: 'builder'
      args:
        POKEMON_API_URL: ${POKEMON_API_URL}
        NODE_ENV: ${NODE_ENV}
    environment:
      POKEMON_API_URL: ${POKEMON_API_URL}
      NODE_ENV: ${NODE_ENV}
    ports:
      - '8081:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: 'npm run dev'

  frontend:
    build:
      context: './frontend'
      target: 'builder'
      args:
        VITE_API_URL: ${VITE_API_URL}
        NODE_ENV: ${NODE_ENV}
    environment:
      VITE_API_URL: ${VITE_API_URL}
      NODE_ENV: ${NODE_ENV}
    ports:
      - '8080:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: 'npm run dev'
    depends_on:
      - backend
